### ISSUE TITLE
咋编译？来点效果图在 README 呗。

### ISSUE THREAD

**Issue by tpoisonooo** [taichi-dev/Taichi-UnityExample#5]

**Comment by PENGUINLIONG** [comment]
You don't have to compile this project because it runs completely on [Unity](https://unity.com/). You can open this project in any recent version of Unity (2020.3.14 or above) and run it in realtime by clicking the play button. If you need to package for Android please consult [the Unity documentation](https://docs.unity3d.com/Manual/android-BuildProcess.html).
